config/routes.rb
Rails.application.routes.draw do

  get 'dashboard', to:'dashboard#index'
  get 'productos', to:'dashboard#productos'
  get 'dashboard/auctions'
  get 'perfil', to:'dashboard#perfil'
  get 'home/index'
  root to: "home#index"
  resources :bids

  #resource :cart, only: [:destroy]
  get 'carrito', to:'cart#show'
  get 'success', to:'cart#pay_success'
  delete 'destroy', to: 'cart#destroy'
  
  resources :auctions do
    member do
      put "like" => "auctions#upvote"
      put "unlike" => "auctions#downvote"
      get :toggle_status
    end
  end
  resources :products
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks' 
  }
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/auction.rb
class Auction < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :bids, dependent: :delete_all
  has_many :order_auctions
  has_many :orders, through: :order_auctions
  validates :product_id, presence: true
  validates :initial_price, presence: true
  
  #votable feature
  acts_as_votable
  
  #create states machines
  include AASM

  aasm column: 'status' do
    state :inactive
    state :active, initial: true
    state :completed
    state :deserted


    event :publish do
      transitions from: :inactive, to: :active
    end

    event :unpublish do
      transitions from: :active, to: :inactive
    end

    event :won do
      transitions from: :active, to: :completed
    end

    event :abandon do
      transitions from: :active, to: :deserted
    end


  end

  #scope show only actives
  #scope :only_active, ->(auction) { where(status: "active")}
  #scope :auction_by, ->(user) { where(user_id: user.id)}



end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_auction, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :toggle_status]
  before_action :blank_auction, only: [:index, :show]

 
  
  

  # GET /auctions
  # GET /auctions.json
  def index
    if( params[:search] && !params[:search].empty? )
      @auctions = Auction.where("title LIKE ?", "%#{params[:search]}%").order(created_at: :desc)  
    else
      if current_user.admin?
        @auctions=Auction.all.order(created_at: :desc)
      else
        @auctions = Auction.filtered_by_user(current_user).order(created_at: :desc)
      end
    end
    @page_title= 'Mis Subastas'
  end

  

  # GET /auctions/1
  # GET /auctions/1.json
  def show

    @auctions=Auction.joins(:product).where(products: {category_id:@auction.product.category_id}).only_active(@auction).uniq
    @countdown_seconds = timediff(DateTime.now.in_time_zone, @auction.end_date.in_time_zone, 1.second)
    @bid_last= Bid.where(auction_id: @auction.id).last
    @bid=@bid_last
    
    @page_title= @auction.title
  end

  #uplike from user
  def upvote
      @auction.upvote_from current_user
      redirect_to root_path
  end
    
  #downlike form user
  def downvote
    @auction.downvote_from current_user
      redirect_to root_path
  end
  
  def toggle_status
    if @auction.active?
      @auction.unpublish!
    else
      @auction.publish!
    end
    redirect_to auctions_url, notice: 'El Estado ha sido actualizado.'
  end

  # GET /auctions/new
  def new
    @page_title= 'Crea tu Subasta'
    @auction = Auction.new
    @products = Product.where(user_id: current_user)
    @product=Product.new

  
    
  end

  def timediff(x,y,method)
    ((y - x)/ method).to_i
  end

  # GET /auctions/1/edit
  def edit
    @page_title= 'Edita tu subasta'
    @auction = Auction.find(params[:id])
    @products = Product.where(user_id: current_user)
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)
    @auction.user = current_user
    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


        

    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def auction_params
      params.require(:auction).permit(:title, :description, :status, :initial_price, :start_date, :end_date, :user_id, :product_id)
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper

  


  def last_bid auction
    @bid_last= Bid.where(auction_id: auction.id).last
    @bid_last.amount
  end

  def placeholder_mas auction
    show_price= 0
    if @bid_last.nil?
      show_price= auction.initial_price + 50
    else
      show_price = @bid_last.amount + 50
    end
    show_price
  end

 

  def translate status
  traduccion= ""
    if status == "active"
      traduccion="activo"
    elsif status =="deserted"
      traduccion="desierta"
    elsif status == "completed"
      traduccion = "terminada"
    elsif status == "inactive"
      traduccion="inactiva"
    end
    traduccion
  end



  
  
end

app/views/auctions/_form.html.erb
<div class="capsule2 mt-5">

  <%= form_with(model: auction, local: true) do |form| %>
     
     <div class="row">

     <div class="form-group col-sm-6">
        <%= form.label "Producto" %>
        <%= form.collection_select :product_id, @products, :id, :title,{prompt: "Selecciona un producto"},{ class:"form-control picker"} %>
        
      </div>
      </div>
      
    <div class="row">

      <div class="form-group col-sm-6">
        <%= form.label "Titulo" %>
        <%= form.text_field :title, class:"form-control" %>
      </div>

      <div class="form-group col-sm-6">
        <%= form.label "Precio Inicial" %>
        <%= form.number_field :initial_price, class:"form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label "Descripciòn" %>
      <%= form.text_area :description, class:"form-control" %>
    </div>

    <div class="row">
    
      <div class="form-group col-sm-6">
        <%= form.label "Fecha de Inicio" %>
        <%= form.datetime_local_field :start_date, class:"form-control" %>
      </div>

      <div class="form-group col-sm-6">
        <%= form.label "Fecha de Finalizaciòn" %>
        <%= form.datetime_local_field :end_date, class:"form-control" %>
      </div>
    </div>

    <div class="row">
            
      <div class="actions col-sm-6 text-center my-auto">
        <%= form.submit "Crear Subasta", class:"btn btn-form btn-block "%>
      </div>
    </div>

  <% end %>
</div>

app/views/auctions/_timer.html.erb
<div class='timer' data-seconds-left=<%= countdown_seconds %>>

app/views/auctions/edit.html.erb
<div class="container m-5">
<div class="tit d-flex flex-column">
<h1 class="title-form">Editar Subasta</h1>
<hr class="titlehr">

<%= render 'form', auction: @auction %>

</div>

app/views/auctions/index.html.erb
<div class="container mt-5">
<h1>Subastas</h1>
    <div class="d-flex justify-content-end">
  <%= link_to 'Nueva Subasta', new_auction_path, class:"btn btn-form" %>
  </div>
  <div class="row">
  <% @auctions.each do |auction| %>
  <div class="col-sm-12 col-md-6">
    <div class="row d-flex justify-content-center">
      <div class="card border-0">
              <div class="row set-p justify-content-center">
                  <div class="col-sm-4 px-0"> <%= image_tag auction.product.image, class:"image" %> </div>
                  <div class="col-sm-8">
                      <div class="row px-3 mt-4 mb-3">
                          <p class="rating mb-0 px-2 mr-3 <%=auction.product.category.color%> "><strong><%=auction.product.category.name%></strong></p>
                          <p class="text-primary mb-0 mr-2 grade"><strong><%=auction.bids.count%> pujas</strong></p>
                          <p class="text-secondary mb-0 mr-2">&middot;</p>
                          <p class="text-secondary mb-0 ml-auto ">estado <%= link_to_if auction.active? || auction.inactive?, translate(auction.status), toggle_status_auction_path(auction), class:auction.status %>   </p>
                      </div>
                      <div class="row px-3">
                          <h3 class="font-weight-bold title"><%= auction.title %></h3>
                      </div>
                      <div class="row px-3">
                          <h5 class="mb-1 description"><%= auction.description %> &nbsp; &vert;&nbsp; Artista: &middot;<%= auction.product.author %></h5>
                      </div>
                      
                         <% if auction.completed?%>
                          <div class="line"></div>
                      <div class="row px-3 mt-3">
                          <h5 class="text-secondary mb-1">Puja Ganadora</h5>
                      </div>
                      <div class="row px-3">
                            <h2 class="text-success mb-1 font-weight-bold price">$<%= last_bid auction %></h2>
                         <%else%>
                      <div class="line"></div>
                      <div class="row px-3 mt-3">
                          <h5 class="text-secondary mb-1">Precio Inicial</h5>
                      </div>
                      <div class="row px-3">
                          <h2 class="text-success mb-1 font-weight-bold price">$<%= auction.initial_price %></h2>
                          <%end%>
                      </div>
                      <div class="row px-3 mb-3">
                          <p class="text-muted mb-0">+ $<%= auction.product.delivery_cost %> costos de envìo</p>
                      </div>
                      <div class="d-flex justify-content-between align-items-center mx-1">
                        <div class="d-flex flex-column justify-content-center align-items-center mx-1">
                            <% if auction.completed?%>
                                <span class="time-words"><%=winner(auction)%></span>
                                <p class="mb-0 text-center plus">Ganador</p>
                            <%elsif auction.deserted?%>
                                <span class="time-words">DESIERTA </span>
                            <%else%>
                            <span class="time-words"><%=distance_of_time_in_words(Time.now,auction.end_date, include_seconds: true, scope: 'datetime.distance_in_words.short')%></span>
                            <p class="mb-0 text-center plus">tiempo restante</p>
                            <%end%>
                        </div>
                        <div class="btn-group float-right my-3" role="group">
                        <%= link_to 'Show', auction, class:"btn btn-outline-secondary btn-grupo", type:"button" %>
                        <%if auction.active? || auction.inactive? %>
                        <%= link_to 'Edit', edit_auction_path(auction), class:"btn btn-outline-secondary btn-grupo", type:"button" %>
                        <%end%>
                        <%= link_to 'Destroy', auction, method: :delete, class:"btn btn-outline-secondary btn-grupo", type:"button", data: { confirm: 'Are you sure?' } %>
                        
                      </div>
                      </div>
                      
                      
                      
                          
                  </div>
                  
              </div>
          </div>
  
    </div>
    
  </div>
  <% end %>
</div>
</div>

app/views/auctions/new.html.erb
<div class="container m-5">
    <div class="row tit d-flex flex-column">
      <h1 class="title-form">Nueva Subasta</h1>
      <hr class="titlehr">
    </div>
  <div class="capsule d-flex  p-5 row">
    <div class="col-sm-1 d-flex flex-column align-items-center">
      <div class="container-balls">
        <div class="uno actives ball  d-flex justify-content-center align-items-center">
          <strong> 1 </strong> 
        </div>
        <div class="dos incomplete ball  d-flex justify-content-center align-items-center">
          <strong> 2 </strong> 
        </div>
        <div class="tres incomplete ball  d-flex justify-content-center align-items-center">
          <strong> 3 </strong> 
        </div>
        <div class="cuatro incomplete ball  d-flex justify-content-center align-items-center">
          <strong> 4 </strong> 
        </div>
        <div class="cinco incomplete ball  d-flex justify-content-center align-items-center">
          <strong> 5 </strong> 
        </div>
        <div class="seis incomplete ball  d-flex justify-content-center align-items-center">
          <strong> 6 </strong> 
        </div>
      </div>
      <div class="scrollBar">
        <span></span>
      </div>
    </div>
    <div class="col-sm-11 px-5">

      <button type="button" class="btn btn-form" data-toggle="modal" data-target="#productModal">Crea un producto</button>

      <div class="capsule2 mt-5">

  <%= form_with(model: @auction, local: true) do |form| %>
     
      
    <div class="row">
    
      <div class="form-group col-sm-12">
        <%= form.label " SELECCIONA EL Producto A SUBASTAR" %>
        <%= form.collection_select :product_id, @products, :id, :title,{prompt: "Selecciona un producto"},{ class:"form-control picker"} %>
        
      </div>
      
      <div class="form-group col-sm-12">
        <%= form.label "ESCOGE EL TITULO DE TU SUBASTA" %>
        <%= form.text_field :title, class:"form-control" %>
      </div>

      <div class="form-group col-sm-12">
        <%= form.label "EL Precio Inicial" %>
        <%= form.number_field :initial_price, class:"form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label "UNA BREVE Descripciòn" %>
      <%= form.text_area :description, class:"form-control" %>
    </div>

    <div class="row">
    
      <div class="form-group col-sm-12 col-md-6">
        <%= form.label "Fecha de Inicio" %>
        <%= form.datetime_local_field :start_date, class:"form-control" %>
      </div>

      <div class="form-group col-sm-12 col-md-6">
        <%= form.label "Fecha de Finalizaciòn" %>
        <%= form.datetime_local_field :end_date, class:"form-control" %>
      </div>
    </div>

    <div class="row">
      
      
      
      
      <div class="actions col-sm-12 text-center my-auto">
        <%= form.submit "Crea tu Subasta", class:"btn btn-form btn-block mt-5 "%>
      </div>
    </div>

  <% end %>
</div>


      <!-- Product modal
      <%= render 'form', auction: @auction %>-->
    </div>
  </div>
</div>


<!-- Product modal-->

<!-- Modal -->
<div class="modal fade" id="productModal" tabindex="-1" aria-labelledby="productModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-electric">
        <h5 class="modal-title ml-5" id="productModalLabel">Nuevo Producto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
        


          <div class="capsule2 p-5">
            <%= form_with(model: Product.new, remote: true) do |form| %>

              <div class="row">
                <div class="form-group col-sm-6 ">
                  <%= form.label "NOMBRE DEL PRODUCTO" %>
                  <%= form.text_field :title , class:"form-control"%>
                </div>
              
                <div class="form-group col-sm-6">
                  <%= form.label "AUTOR" %>
                  <%= form.text_field :author, class:"form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= form.label "DESCRIPCION" %>
                <%= form.text_area :description, class:"form-control" %>
              </div>

              <div class="row">
              
                <div class="form-group col-sm-6">
                  <%= form.label "PRECIO" %>
                  <%= form.number_field :initial_price, class:"form-control" %>
                </div>

                <div class="form-group col-sm-6">
                  <%= form.label "COSTO DE ENVIO" %>
                  <%= form.number_field :delivery_cost, class:"form-control" %>
                </div>
              </div>

              <div class="row">
              
                <div class="form-group col-sm-6">
                  <%= form.label "IMAGEN" %>
                  <%= form.file_field :image, class:"form-control-file" %>
                </div>

                <div class="form-group col-sm-6">
                  <%= form.label "CATEGORIA" %>
                  <%= form.collection_select :category_id, Category.all, :id, :name,{prompt: "Selecciona una categoria"},{ class:"form-control"} %>
                </div>
              </div>

              <div class="actions mt-5">
                <%= form.submit "Crea el Producto", class:"btn btn-form btn-block" %>
              </div>
            <% end %>
          </div>


      </div>
      
    </div>
  </div>
</div>

app/views/auctions/show.html.erb
<div class="row">
<div class="col-sm-12 col-md-5 d-flex justify-content-center">
  <div class="card" style="width: 24rem;">
    <%= image_tag @auction.product.image.variant(resize:"400"), class:"card-img-top"%>
    <div class="card-body">
      <h5 class="title-show mt-3"><%= @auction.title %></h5>
      <p class="text-secondary"> Artista: <%=@auction.product.author%></p>
      <hr>
        <p class="text-secondary my-4">Descripciòn: <%= @auction.description %></p>
      
    </div>
  </div>
</div>
<div class="col-sm-12 col-md-7">
    <div class="card" style="width: 36rem;">
      <div class="card-body">
        
        <h3 class="finaliza"> Esta Subasta finaliza el <strong><%=l(@auction.end_date, :format => '%d %B %Y')%></strong></h3>
        <div class="contador d-flex justify-content-center my-5">
        
        <% if !@auction.winner_id.present?%>
          <%= render 'timer', countdown_seconds: @countdown_seconds %>
        <%else%>
          <div id="finalizada"><p>Subasta finalizada</p>
            <% if @auction.deserted?%>
            <p class="text-secondary3"> Estuviste a punto de ganarla</p>
            <%else%>
            <p class="text-secondary3"> El ganador de la subasta fuè <strong> <%= winner(@auction)%></strong></p>
            <%end%>
          </div>
        <%end%>
        </div>
        </div>
            <hr>
        <div class="row info-bid d-flex justify-content-between">
          <% if (@auction.bids.last).nil?%>
          <p class="current_bid text-secondary px-5">Puja Ahora !!</p>
          <%else%>
          <p class="current_bid text-secondary px-5"> <strong>Ultima puja por:</strong>  <%=@auction.bids.last.user.name%></p>
          <%end%>

          <p class="bids_num text-secondary px-5"> <%=@auction.bids.count%> Pujas</p>
        </div>
        <div class="bid-container text-center ">
        <p class="current text-secondary mb-0">
        Puja Actual
        </p>
          <div id="biddes" class="biddes-class text-center">
            <% if @bid.nil?%>
              <h2><%=  number_to_currency(@auction.initial_price, :precision => 0, :delimiter => ".")   %></h2>
            <% else%>
              <%= render @bid %>
            <% end%>
          </div>
        </div>
        <form class="text-center my-4">
          
          <input type="text" class="write-bid" data-behavior="auction_speaker" data-auction="<%= @auction.id %>" placeholder="<%= placeholder_mas(@auction) %>">
          
        </form>
      </div>
    </div>
</div>
<%#= link_to 'Edit', edit_auction_path(@auction) %> 
<%#= link_to 'Back', auctions_path %>

</div>
<div class="tit d-flex flex-column mt-5">
<h1 class="title-form mt-5">Subastas Relacionadas</h1>
<hr class="titlehr">
<div class="row mt-2 d-flex flex-column justify-content-center">
  <%= render 'shared/featured', auctions: @auctions%>
</div>