config/routes.rb
Rails.application.routes.draw do

  get 'dashboard', to:'dashboard#index'
  get 'productos', to:'dashboard#productos'
  get 'dashboard/auctions'
  get 'perfil', to:'dashboard#perfil'
  get 'home/index'
  root to: "home#index"
  resources :bids

  #resource :cart, only: [:destroy]
  get 'carrito', to:'cart#show'
  get 'success', to:'cart#pay_success'
  delete 'destroy', to: 'cart#destroy'
  
  resources :auctions do
    member do
      put "like" => "auctions#upvote"
      put "unlike" => "auctions#downvote"
      get :toggle_status
    end
  end
  resources :products
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks' 
  }
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_featured.html.erb
<div class="owl-carousel owl-theme">

  <% auctions.each do |auction| %>
  <div class="col-sm-12 item">
    <div class="row d-flex justify-content-center">
      <div class="card border-0 ">
              <div class="row set-p justify-content-center">
                  <div class="col-sm-4 px-0"> <%= image_tag auction.product.image, class:"image" %> </div>
                  <div class="col-sm-8">
                      <div class="row px-3 mt-4 mb-3">
                          <p class="rating2 mb-0 px-2 mr-3 <%=auction.product.category.color%> "><strong><%=auction.product.category.name%></strong></p>
                          <p class="text-primary mb-0 mr-2 grade"><strong><%=auction.bids.count%> pujas</strong></p>
                          <p class="text-secondary mb-0 mr-2">&middot;</p>
                          
                      </div>
                      <div class="row px-3">
                          <h3 class="font-weight-bold title-fet"><%= auction.title %></h3>
                      </div>
                     
                      
                         <% if auction.completed?%>
                          <div class="line"></div>
                      <div class="row px-3 mt-3">
                          <h5 class="text-secondary2 mb-1">Puja Ganadora</h5>
                      </div>
                      <div class="row px-3">
                            <h2 class="text-success mb-1 font-weight-bold price">$<%= last_bid auction %></h2>
                         <%else%>
                      <div class="line"></div>
                      <div class="row px-3 mt-3">
                          <h5 class="text-secondary2 mb-1">Precio Inicial</h5>
                      </div>
                      <div class="row px-3">
                          <h2 class="text-success mb-1 font-weight-bold price">$<%= auction.initial_price %></h2>
                          <%end%>
                      </div>
                      
                      <div class="d-flex justify-content-between align-items-center mx-1">
                        
                        
                        <div class="my-3 d-flex ml-auto" >
                        <%= link_to 'Pujar', auction, class:"btn btn-outline-success button-search ", type:"button" %>
                        
                        
                      </div>
                      
                      </div>
                      
                      
                      
                          
                  </div>
                  
              </div>
          </div>
  
    </div>
    
  </div>
  <% end %>
</div>

<div class="owl-nav text-center">

       
</div>
</div>

app/views/shared/_footer.html.erb
<footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6">
            <div class="footer-info">
              <%= image_tag '250X83_WHITE', class:"footer-brand" %>
                            
              <p class="pb-3"><em>Qui repudiandae et eum dolores alias sed ea. Qui suscipit veniam excepturi quod.</em></p>
              <p>
                Rancagua <br>
                2820000, Chile<br><br>
                <strong>Phone:</strong> +569 5589 5548<br>
                <strong>Email:</strong> info@subastart.com<br>
              </p>
              <div class="social-links mt-3">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Servicios</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Inicio</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Subastas</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Productos</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terminos y condiciones</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Contacto</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Links Utiles</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Inicio</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Subastas</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Productos</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terminos y condiciones</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Contacto</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Escribenos</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Enviar">
            </form>

          </div>

        </div>
      </div>
    </div>

    
  </footer>

app/views/shared/_navbar.html.erb
<nav id="header" class="navbar sticky-top navbar-expand-lg navbar-light">
<div class="container">
  <%= link_to  root_path ,class:"brand-container" do%>
  <%= image_tag '250X83_COLOR', class:"navbar-brand img-fluid" %>
  <%end%>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">

      <li class="nav-item">
        <%= link_to 'Inicio', root_path, class:"nav-link hvr-underline-from-center " %>
      </li>
      <% if user_signed_in? %>
         <li class="nav-item dropdown">
         
            <a class="nav-link dropdown-toggle hvr-underline-from-center" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Mis Subastas
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Mis Subastas', auctions_path, :class => 'dropdown-item'  %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Mis Productos', products_path, :class => 'dropdown-item' %> 
              <div class="dropdown-divider"></div>
              <%= link_to "Carrito", carrito_path, :class => 'dropdown-item'  %>
            
            </div>
            
            
        </li>

        
         <li class="nav-item dropdown">
         
            <a class="nav-link dropdown-toggle hvr-underline-from-center" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Mi perfil
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Ver mi perfil", perfil_path, :class => 'dropdown-item'  %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'dropdown-item' %> 
            </div>
            
            
        </li>

       
         

        <% if current_user.admin?%>
        <li class="nav-item dropdown">
         
            <a class="nav-link dropdown-toggle hvr-underline-from-center" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dashboard
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, :class => 'dropdown-item'  %>
              <div class="dropdown-divider"></div>
              <%= link_to "Productos", productos_path, :class => 'dropdown-item'  %> 
              <div class="dropdown-divider"></div>
              <%= link_to "Subastas", dashboard_auctions_path, :class => 'dropdown-item'  %> 
              </div>
            
            
        </li>

        <%end%>
       
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link hvr-underline-from-center'  %>
        </li>

        <li class="nav-item">
          <%= link_to carrito_path, :class => 'nav-link hvr-underline-from-center' do %>
            <i class="lni lni-lg lni-cart"></i>
          <%end%>
        </li>
       
      <% else %>
        <li class="nav-item">
          <%= link_to "Registro", new_user_registration_path, :class => 'nav-link hvr-underline-from-center'  %> 
        </li>
        <li class="nav-item">
          <%= link_to "Inicio Sesiòn", new_user_session_path, :class => 'nav-link hvr-underline-from-center'  %>
        </li>
      <% end %>
      
        
     
    
    </ul>

    <% if controller_name == 'home' && action_name == 'index' %>
    
      <%= form_tag(root_path, :method => "get",   
          class: 'form-inline my-2 my-lg-0') do %>  
        <div class="input-group ">  
          <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control  input-search" %>  
          <div class="input-group-append">  
            <%= button_tag :class => 'btn btn-outline-success my-sm-0 button-search text-center',:name => nil do%> 
            <i class="lni lni-lg lni-search-alt"></i> 
            <%end%>
          </div>  
        </div>  
      <% end %>
    <%else%>
     
    <%end%>
    
  </div>
  </div>
</nav>
  

  

app/views/shared/_navdashboard.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbarBg">
<div class="container">
  <%= link_to 'Subastar', root_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">

      <li class="nav-item">
        <%= link_to 'Inicio', root_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
          <%= link_to 'Mis Subastas', auctions_path, :class => 'nav-link' %> 
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Mi perfil", perfil_path, :class => 'nav-link'  %>
        </li>
         <li class="nav-item">
          <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'nav-link' %> 
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, :class => 'nav-link'  %>
          </li>
        <li class="nav-item">
          <span class="nav-link">Bienvenido <strong><%= current_user.name %></strong>.</span>
        
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %> 
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
        </li>
      <% end %>
      
        
     
    
    </ul>
    

    
  </div>
  </div>
</nav>

app/views/shared/_topbar.html.erb
<div id="topbar" class="d-none d-lg-flex align-items-center fixed-top">
    <div class="container d-flex">
      <div class="contact-info ml-auto d-flex">
      <%if signed_in?%>
        <span class="top-bar-text mr-5">Bienvenido <strong><%= current_user.name %></strong>.</span>
      <%end%>
        
      <div class="social-links ">
        <a href="#" class="twitter"><i class="lni lni-twitter-original"></i></a>
        <a href="#" class="facebook"><i class="lni lni-facebook-original"></i></a>
        <a href="#" class="instagram"><i class="lni lni-instagram-original"></i></a>
        <a href="#" class="skype"><i class="lni lni-skype"></i></a>
        <a href="#" class="linkedin"><i class="lni lni-linkedin-original"></i></a>
      </div>
      </div>
    </div>
  </div>